# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
sudo: false

cache: packages

install: travis_wait 30 mvn install

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

