# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'CODECOV_TOKEN="31ebd220-3f2e-461b-93b0-456acd7537a8"'
  - Rscript -e 'library(covr); codecov()'
