// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tidy_bom
std::string tidy_bom(std::string df);
RcppExport SEXP _hansard_tidy_bom(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(tidy_bom(df));
    return rcpp_result_gen;
END_RCPP
}
